## Instructions
*   Attempt all questions.
*   Submit the completed assignment in .ipynb format.
*   Use appropriate function definitions and comments for clarity.

## Assignment Questions:

# Section A: *Data Structures & Control Structures*

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
3. Create a set of integers with some duplicate values. Print the set and explain the output.
4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
6. Given a 'marks' variable, print the grade:

*  90 and above: 'A'
*  75–89: 'B'
*  50–74: 'C'
*  Below 50: 'Fail'

7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

##### 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
# List of 5 integer value

x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [ ]:
type(x) # this provides the type of variable.

list

In [ ]:
# Append

x.append([6,7]) # add the given numbers to the end of the list but in the format given.
x

[1, 2, 3, 4, 5, [6, 7]]

In [ ]:
# Extend

x.extend([8,9]) # just adds values provided at the end individually
x

[1, 2, 3, 4, 5, [6, 7], 8, 9]

In [ ]:
# Insert

x.insert(2,2.5)  # inserts the value at 2nd position which at the position where there is 3 but moves 3 and other numbers to the next position.
x

[1, 2, 2.5, 3, 4, 5, [6, 7], 8, 9]

In [ ]:
# Remove

x.remove([6,7]) # removes the selected number from the list.
x

[1, 2, 2.5, 3, 4, 5, 8, 9]

In [ ]:
# Pop

x.pop() # will automatically remove the last number in the list.
x

[1, 2, 2.5, 3, 4, 5, 8]

In [ ]:
# Clear

x.clear() # deletes the complete list.
x

[]

In [ ]:
# Index

x=[1,2,3,4,5]

element = x.index(3) # this gives the position of number 3 in the list which is 2.
element

2

In [ ]:
# Count

x=[1,2,2,3,4,5]

count_2=x.count(2)  # this function gives the count of values of selected number. in this case selection was made for count of number 2 and the result was 2 since there are 2 quantity of 2 in the list.
count_2

2

In [ ]:
# Sort

x=[1,3,6,2,4,5]

x.sort() # this rearranges the numbers in ascending order in the list if the numbers are not arranged in ascending sequence.
x

[1, 2, 3, 4, 5, 6]

In [ ]:
# Reverse

x=[1,3,6,2,4,5]

x.reverse() # this function reverses the complete list as it is from right to left.
x

[5, 4, 2, 6, 3, 1]

#### 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why?

In [ ]:
y=('Alex','Bob','Carol')
y

('Alex', 'Bob', 'Carol')

In [ ]:
type(y)

tuple

#### Observation for the below Type Error:
##### 1. Tuples are immutable, which means their elements cannot be changed after the tuple is created. Unlike the lists, which are mutable and allow modifications liek adding, removing or changing elements.
##### 2. Tuples are designed to be fixed sequence data.
##### 3. TypeError: ('str' object does not support item assignment) because we are trying to assign a new value to a specific index within tuple, which are not allowed for data types are tuples.

In [ ]:
y[1]='Megan'
y

TypeError: 'tuple' object does not support item assignment

#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
# Using Sets

S={10,22,34,41,41,22,52,10,23,34}
S

{10, 22, 23, 34, 41, 52}

### Observations:
#### Sets are used when the given array has numbers not in a sequence. To bring them in sequence and to get single count, sets are used.

#### as we can see above that the numbers in the array are not in a sequence and numbers like 10, 22, 34 and 41 are repeated still output was single count.

#### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [2]:
# Creating a Dictionary

d1={'name':['Alex','Rob','Clara'],'age':[25,26,23],'city':['New York','Los Angeles','Boston']}
d1.keys()
d1.values()
d1

{'name': ['Alex', 'Rob', 'Clara'],
 'age': [25, 26, 23],
 'city': ['New York', 'Los Angeles', 'Boston']}

In [3]:
# Updating the age of Clara

d1['age'][2]=21
d1

{'name': ['Alex', 'Rob', 'Clara'],
 'age': [25, 26, 21],
 'city': ['New York', 'Los Angeles', 'Boston']}

In [4]:
# adding a new key (Email) to the Dictionary

d1['email']=['alex.a@gmail.com','rob.b@gmail.com','clara.c@gmail.com']
d1

{'name': ['Alex', 'Rob', 'Clara'],
 'age': [25, 26, 21],
 'city': ['New York', 'Los Angeles', 'Boston'],
 'email': ['alex.a@gmail.com', 'rob.b@gmail.com', 'clara.c@gmail.com']}

#### 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
# To determine the if the person is eligible to vote (age>=18)
# Taking age as variable

age=int(input("Enter your age: "))

# To check if the voter's age is (>=18 or not)

if age >= 18:
  print("You are eligible to Vote")
else:
  print("You are not eligible to Vote.")

Enter your age: 16
You are not eligible to Vote.


#### 6. Given a 'marks' variable, print the grade:
*  90 and above: 'A'
*  75–89: 'B'
*  50–74: 'C'
*  Below 50: 'Fail'

In [ ]:
# To determin the Grade:

Grade=int(input("Enter your marks: "))

# To check the marks entered:

if Grade >= 90:
  print("Your Grade is A")
elif Grade >= 75 and Grade <= 89:
  print("Your Grade is B")
elif Grade >= 50 and Grade <= 74:
  print("Your Grade is C")
else:
  print("Your Grade is Fail")

Enter your marks: 49
Your Grade is Fail


### 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
# To check if number is positive and also if it is even

number=int(input("Enter a number: "))

if number > 0:
  if number % 2 == 0:
    print("The number is positive and even.")
  else:
    print("The number is positive but odd.")

# to check if the number is zero or negative

elif number == 0:
  print("The number is zero.")
else:
  print("The number is negative.")

Enter a number: 44
The number is positive and even.


In [ ]:
# To check if number is positive and also if it is even

number=int(input("Enter a number: "))

if number > 0:
  if number % 2 == 0:
    print("The number is positive and even.")
  else:
    print("The number is positive but odd.")

# to check if the number is zero or negative

elif number == 0:
  print("The number is zero.")
else:
  print("The number is negative.")

Enter a number: 0
The number is zero.


In [ ]:
# To check if number is positive and also if it is even

number=int(input("Enter a number: "))

if number > 0:
  if number % 2 == 0:
    print("The number is positive and even.")
  else:
    print("The number is positive but odd.")

# to check if the number is zero or negative

elif number == 0:
  print("The number is zero.")
else:
  print("The number is negative.")

Enter a number: -21
The number is negative.


## Section B: *Numpy*

8. Create:

*  A scalar using np.array(5)
*  A 1D array with values 1 to 5
*  A 2D array (2x3) with values from 10 to 60 in steps of 10

9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

### 8. Create:
*  A scalar using np.array(5)
*  A 1D array with values 1 to 5
*  A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
import numpy as np

# A scalar using np.array(5)

scalar=np.array(5)
scalar

array(5)

In [ ]:
import numpy as np

# A 1D array with values 1 to 5

data=np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np

# A 2D array (2X3) with values from 10 to 60 in steps of 10

data=np.array([[10,20,30],[40,50,60]])
data

array([[10, 20, 30],
       [40, 50, 60]])

#### 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
import numpy as np

data=np.random.randint(0,100,(4,4))
data

array([[94, 77, 21, 60],
       [96, 51, 48, 49],
       [61, 83, 63, 66],
       [82, 95, 33, 61]])

#### 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

# to create 2D numpy array of shape (3X3)

data=np.array([[1,2,3],[5,6,7],[8,9,10]])
data

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# to conver it into dataFrame with column: 'A','B','C'

df=pd.DataFrame(data,columns=['A','B',"c"])
df

A  B   c
0  1  2   3
1  5  6   7
2  8  9  10

## Section C: *Exploring Pandas*
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.

Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [5]:
import numpy as np
import pandas as pd

In [71]:
# Create a small DataFrame manually with 10 rows and columns: "Name", "Age", "City", "Salary"

data=pd.DataFrame({"Name":['Alex','Amar', 'Chanakya', 'Shipra', 'Tanvi', 'Saprushi', 'Viplove', 'Zenab', 'Chanakya', 'Karan'],"Age":[25,35,34,35,32,41,37,45,34,33],"City":['New York','Los Angeles','Boston','Chicago','Houston','Phoenix','Philadelphia','San Antonio','Boston','Dallas'],"Salary":[70000,80000,np.nan,85000,82000,90000,88000,95000,80000,78000]})

In [72]:
data
data.head()

Name  Age         City   Salary
0      Alex   25     New York  70000.0
1      Amar   35  Los Angeles  80000.0
2  Chanakya   34       Boston      NaN
3    Shipra   35      Chicago  85000.0
4     Tanvi   32      Houston  82000.0

In [73]:
# .info()

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [74]:
# .describe()

data.describe()

Age        Salary
count  10.000000      9.000000
mean   35.100000  83111.111111
std     5.321863   7372.998787
min    25.000000  70000.000000
25%    33.250000  80000.000000
50%    34.500000  82000.000000
75%    36.500000  88000.000000
max    45.000000  95000.000000

In [75]:
# drop city column

data.drop('City',axis=1)

Name  Age   Salary
0      Alex   25  70000.0
1      Amar   35  80000.0
2  Chanakya   34      NaN
3    Shipra   35  85000.0
4     Tanvi   32  82000.0
5  Saprushi   41  90000.0
6   Viplove   37  88000.0
7     Zenab   45  95000.0
8  Chanakya   34  80000.0
9     Karan   33  78000.0

In [80]:
# fill any missing value in salary colum with the mean

data['Salary'].fillna(data['Salary'].mean(),inplace=True)
data

/tmp/ipython-input-833291903.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Salary'].fillna(data['Salary'].mean(),inplace=True)


Name  Age          City  Salary
0      Alex   25      New York   70000
1      Amar   35   Los Angeles   80000
2  Chanakya   34        Boston   80000
3    Shipra   35       Chicago   85000
4     Tanvi   32       Houston   82000
5  Saprushi   41       Phoenix   90000
6   Viplove   37  Philadelphia   88000
7     Zenab   45   San Antonio   95000
8  Chanakya   34        Boston   80000
9     Karan   33        Dallas   78000

In [82]:
# remove any duplicate row

data.drop_duplicates(inplace=True)
data

Name  Age          City  Salary
0      Alex   25      New York   70000
1      Amar   35   Los Angeles   80000
2  Chanakya   34        Boston   80000
3    Shipra   35       Chicago   85000
4     Tanvi   32       Houston   82000
5  Saprushi   41       Phoenix   90000
6   Viplove   37  Philadelphia   88000
7     Zenab   45   San Antonio   95000
9     Karan   33        Dallas   78000